version: '3.8'

volumes:
  db_storage:
    driver: local
    labels:
      description: "Postgres data volume"

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db_storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Exposing the default Postgres port
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
