version: '3.8'

volumes:
  redis_storage:
    driver: local
    labels:
      description: "Redis data volume"

services:
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_storage:/data
    ports:
      - "6379:6379"  # Exposing the default Redis port
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
